registration:
  path: /register
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:registration }

_registration_completed:
  path: /registration_completed
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:registrationCompleted }

adminLogin:
  path: /admin
  defaults: { _controller: ViktorijaVikaBudgetBundle:Default:admin }

login_route:
  path:     /login
  defaults: { _controller: ViktorijaVikaBudgetBundle:Security:login }

login_check:
  path: /login_check
      # no controller is bound to this route
      # as it's handled by the Security system

logout:
  path: /logout

usersspending:
  path: /usersspending/
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserExpenses:usersSpending }

expenses_in_detail:
  path: /detailed_expenses
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserExpenses:detailedExpenses }

expenses_chart:
  path: /expenses_chart
  defaults: { _controller: ViktorijaVikaBudgetBundle:ExpensesStatistics:showExpensesChart }

users_income:
  path: /usersincome
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserIncome:usersIncome }

keitimas:
  path: /update/{id}
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:update }

test:
  path: /test
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:createExpense }

show_expense:
  path: /showexpenses/{id}
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:showExpense }

show_people:
  path: /showpeople/{id}
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:showPeople }

jQuery_test:
  path: /testjquery
  defaults: { _controller: ViktorijaVikaBudgetBundle:TestJQuery:test }

ajax_test:
  path: /testajax
  defaults: { _controller: ViktorijaVikaBudgetBundle:TestJQuery:ajaxResponse }
