registration:
  path: /
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:registration }

_registration_completed:
  path: /registration_completed
  defaults: { _controller: ViktorijaVikaBudgetBundle:Registration:registrationCompleted }

login_route:
  path:     /login
  defaults: { _controller: ViktorijaVikaBudgetBundle:Security:login }

login_check:
  path: /login_check
      # no controller is bound to this route
      # as it's handled by the Security system

logout:
  path: /logout

users_income:
  path: /users_income
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserIncome:calculateIncome }

renew_income:
  path: /renew_income
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserIncome:renewIncome }

users_expenses:
  path: /users_expenses
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserExpenses:calculateExpenses }

renew_expenses:
  path: /renew_expenses
  defaults: { _controller: ViktorijaVikaBudgetBundle:ShowUserExpenses:renewExpenses }

savings:
  path: /savings
  defaults: { _controller: ViktorijaVikaBudgetBundle:Savings:showSavings }

expenses_chart:
  path: /expenses_chart
  defaults: { _controller: ViktorijaVikaBudgetBundle:ExpensesStatistics:showExpensesChart }




