<?php

namespace Viktorija\VikaBudgetBundle\Entity\InDetail;

use Doctrine\ORM\EntityRepository;

/**
 * ExpensesInDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpensesInDetailRepository extends EntityRepository
{

//    public function findAllOrderedByName()
//    {
//        return $this->getEntityManager()
//            ->createQuery(
//                'SELECT p FROM ViktorijaVikaBudgetBundle:InDetail:ExpensesInDetail p ORDER BY p.id ASC'
//            )
//            ->getResult();
//    }

}
